### ISSUE TITLE
Easy Window Dragging link is broken

### ISSUE THREAD

**Issue by EdwinHoksberg** [chx/chx.github.io#1]
Hi,

The link in your wiki to the page "https://hotkeyit.github.io/v2/docs/scripts/EasyWindowDrag_[KDE].htm" is invalid, it should be changed to: "https://hotkeyit.github.io/v2/docs/scripts/EasyWindowDrag_(KDE).htm"

**Comment by chx** [comment]
Thanks, fixed!
